### ISSUE TITLE
Verification failed when install  iso-3166-1-alpha-2

### ISSUE THREAD

**Issue by ngloom** [georgzoeller/iso-3166-1-alpha-2#4]
Error Occurs when npm install the latest  facebook-nodejs-business-sdk which depend on the iso-3166-1-alpha-2,  error detail is as below :

> npm ERR! code EINTEGRITY
> npm ERR! Verification failed while extracting iso-3166-1-alpha-2@1.0.0:
> npm ERR! Verification failed while extracting iso-3166-1-alpha-2@1.0.0:
>  npm ERR! sha1-vJ4LuU5YTfVGipMpl6KFUuJvl6w= integrity checksum failed when using sha1: wanted sha1-vJ4LuU5YTfVGipMpl6KFUuJvl6w= but got sha512-0h1y/thPDkZcTmW7synJwtxbAMFXGhDhdcnz9McwLKgfeMJ95K/MoTYaTM3KwWlTqPln/EQu0OQUz82u+Z1Imw== sha1-5DQHBvMCWqZs2qpe8X8E34BdKk4=. (130894 bytes)
> npm WARN tarball tarball data for facebook-nodejs-business-sdk@latest (sha1-u8UdGN9oHPdSNRnsyEYbWx5dHVU=) seems to be corrupted. Trying one more time.

Both npm in node 8 and node 12 failed with same error.
Help needed & thanks a lot

**Comment by georgzoeller** [comment]
I contacted the people maintaining that SDK to see whats up

**Comment by ngloom** [comment]
@georgzoeller  Great, thanks a lot ~

**Comment by ngloom** [comment]
@georgzoeller  the install process is ok today , thanks very much !
