### ISSUE TITLE
Netherlands Antilles (AN) and Kosovo (XK) do not exist

### ISSUE THREAD

**Issue by utschenik** [georgzoeller/iso-3166-1-alpha-2#5]
Hello,

is it possible that you extend your country list with the countries Netherlands Antilles (AN) and Kosovo (XK)?

Netherlands Antilles is a composite of three different countries under the supervision of the Netherlands. The country code is reserved until 2060 (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)

Kosovo (XK) has an temporary country code, which is used from the european commision as an identifier. (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)

Would be great if the both countries could be added.
Thank you

**Comment by georgzoeller** [comment]
Feel free to send a PR
