### ISSUE TITLE
Prototype Pollution vulenrability in dependency

### ISSUE THREAD

**Issue by andrew-itscript** [georgzoeller/iso-3166-1-alpha-2#7]
![Desktop 2021-04-14 15-42-35](https://user-images.githubusercontent.com/29883742/114681222-23d7b280-9d38-11eb-8ad8-d94e97b4625d.png)

https://app.snyk.io/test/npm/iso-3166-1-alpha-2/1.0.0

**Comment by gryphon2411** [comment]
@georgzoeller can you please update `mout` package?

**Comment by georgzoeller** [comment]
Not using either of the vulnerable functions.
