### ISSUE TITLE
Publish newer version of this package to npm

### ISSUE THREAD

**Issue by kennhung** [georgzoeller/iso-3166-1-alpha-2#9]
Hi, 
Could you publish the newer version this package to npm?
It seems that the version on npm is still the old one.

**Comment by georgzoeller** [comment]
Yes, when back at my computer.

That said the vulnerability doesn’t actually affect anything in the package
when used by default, so this is only housekeeping.

**Comment by kostya-yaremenko** [comment]
Hey,
Please, publish the newer version of this package to npm.

**Comment by harivigneshr** [comment]
Hi,
Please publish the newer version of this package to npm

**Comment by Mattinn** [comment]
Hey @georgzoeller  I see the `mout` patch was merged 9 months ago but not released, any chance you could do that?

**Comment by georgzoeller** [comment]
published
